site_name: ReCoDE Diffusion Code
theme:
  # recommend leaving this as is
  name: material
  # favicon: favicon.png

  # change as appropriate
  palette:
    primary: blue grey
    accent: green

  # SPA behaviour
  features:
    - navigation.instant
    - navigation.top

plugins:
  - tags
  - search
  - include-markdown # https://github.com/mondeja/mkdocs-include-markdown-plugin

markdown_extensions:
  - meta
  - mdx_math:
      enable_dollar_delimiter: True
  - pymdownx.highlight:
      anchor_linenums: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
