module Output_Mod

  use Constants_Mod
  use Problem_Mod
    !! $$ Exercise 2b
  use Materials_Mod
    !!Handles the data generated by solver routines, generating data readable by paraview etc
    !!Any other postprocessing of data would also go here

  implicit none
  public :: GenerateVTU
  type, public :: t_output

  end type
contains

  subroutine GenerateVTU(Problem, Material, Flux)
    type(t_problem) :: Problem
    !! $$ Exercise 2b
    type(t_material), dimension(:) :: Material
    integer :: ii, jj, N_Nodes, N_Regions, NodeID
    integer, allocatable, dimension(:) :: RegionNodes
    integer, parameter :: textfile = 201, vtufile = 202
    real(kind=dp) :: Position
    real(kind=dp), allocatable, dimension(:) :: Flux, Boundary_Pos
    !! $$ Exercise 2b
    real(kind=dp) :: Absorption, Source

    !!Extract relevant problem information
    N_Regions = Problem%GetN_Regions()
    allocate(RegionNodes(N_Regions), Boundary_Pos(N_Regions))
    Boundary_Pos = Problem%GetBoundary_Pos()
    RegionNodes = Problem%GetNodes()
    N_Nodes = Problem%GetN_Nodes()

    !!Generate textfile
    open(textfile, File='OutputFile.txt', Status='Replace')
    Position = 0._dp
    !!First node
    NodeID = 1
    write(textfile, '(2E14.6)') Position, Flux(NodeID)
    do ii = 1, N_Regions
      do jj = 1, RegionNodes(ii) - 1
        NodeID = NodeID + 1
        Position = Position + (Boundary_Pos(ii + 1) - Boundary_Pos(ii))/real(RegionNodes(ii) - 1, dp)
        write(textfile, '(2E14.6)') Position, Flux(NodeID)
      end do
    end do
    close(textfile)

    !!Generate VTU file
    open(vtufile, File='OutputFile.vtu', Status='Replace')

    !!Describe the format
    write(vtufile, '(g0)') "<?xml version=""1.0""?>"
    write(vtufile, '(g0)') "<VTKFile type=""UnstructuredGrid"" version=""0.1"" byte_order=""LittleEndian"">"
    write(vtufile, '(g0)', advance='no') "  "
    write(vtufile, '(g0)') "<UnstructuredGrid>"

    !!Describe the amount of data
    write(vtufile, '(g0)', advance='no') "    "
    write(vtufile, '(g0)', advance='no') '<Piece NumberOfPoints="'
    write(vtufile, '(g0)', advance='no') N_Nodes*2
    write(vtufile, '(g0)', advance='no') '" NumberOfCells="'
    write(vtufile, '(g0)', advance='no') N_Nodes - 1
    write(vtufile, '(g0)') '">'

    !!Fill in the point data
    write(vtufile, '(g0)', advance='no') "      "
    write(vtufile, '(g0)') '<PointData Scalars="flux">'

    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)') '<DataArray Name="flux" format="ascii" type="Float64" >'
    write(vtufile, '(g0)', advance='no') "          "
    !!Flux values
    do ii = 1, N_Nodes
      write(vtufile, '(E14.6)', advance='no') Flux(ii)
      write(vtufile, '(g0)', advance='no') " "
    end do
    !!Copy of flux to be smeared in y
    do ii = 1, N_Nodes
      write(vtufile, '(E14.6)', advance='no') Flux(ii)
      write(vtufile, '(g0)', advance='no') " "
    end do

    write(vtufile, '(g0)') ""
    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)') "</DataArray>"

    write(vtufile, '(g0)', advance='no') "      "
    write(vtufile, '(g0)') "</PointData>"

    !!Cell data section
    write(vtufile, '(g0)', advance='no') "      "
    !! $$ Exercise 2b
    write(vtufile, '(g0)') '<CellData Scalars="Region, Cell, Absorption, Source">'

    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)') '<DataArray Name="Region" format="ascii" type="Int32" >'
    write(vtufile, '(g0)', advance='no') "          "

    !!Loop over the problem to find the region number
    do ii = 1, N_Regions
      do jj = 1, RegionNodes(ii) - 1
        write(vtufile, '(g0)', advance='no') ii
        write(vtufile, '(g0)', advance='no') " "
      end do
    end do
    write(vtufile, '(g0)') ""
    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)') "</DataArray>"

    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)') '<DataArray Name="Cell" format="ascii" type="Int32" >'
    write(vtufile, '(g0)', advance='no') "          "

    do ii = 1, N_Nodes - 1
      write(vtufile, '(g0)', advance='no') ii
      write(vtufile, '(g0)', advance='no') " "
    end do
    write(vtufile, '(g0)') ""
    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)') "</DataArray>"

    !! $$ Exercise 2b
    !!Loop over the problem to find the absorption and source
    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)') '<DataArray Name="Absorption" format="ascii" type="Float64" >'
    write(vtufile, '(g0)', advance='no') "          "
    do ii = 1, N_Regions
      Absorption = Material(ii)%GetSig_a()
      do jj = 1, RegionNodes(ii) - 1
        write(vtufile, '(E14.6)', advance='no') Absorption
        write(vtufile, '(g0)', advance='no') " "
      end do
    end do
    write(vtufile, '(g0)') ""
    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)') "</DataArray>"
    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)') '<DataArray Name="Source" format="ascii" type="Float64" >'
    write(vtufile, '(g0)', advance='no') "          "
    do ii = 1, N_Regions
      Source = Material(ii)%GetS()
      do jj = 1, RegionNodes(ii) - 1
        write(vtufile, '(E14.6)', advance='no') Source
        write(vtufile, '(g0)', advance='no') " "
      end do
    end do
    write(vtufile, '(g0)') ""
    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)') "</DataArray>"

    write(vtufile, '(g0)', advance='no') "      "
    write(vtufile, '(g0)') "</CellData>"

    !!Fill in the point data
    write(vtufile, '(g0)', advance='no') "      "
    write(vtufile, '(g0)') "<Points>"
    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)') "<DataArray Name=""Coordinates"" NumberOfComponents=""3"" format=""ascii"" type=""Float64"" >"
    write(vtufile, '(g0)', advance='no') "          "
    !!1 dimensional flux results
    Position = 0._dp
    do ii = 1, N_Regions
      do jj = 1, RegionNodes(ii) - 1
        write(vtufile, '(E14.6)', advance='no') Position
        write(vtufile, '(g0)', advance='no') " 0.000000E+00 0.000000E+00 "
        Position = Position + (Boundary_Pos(ii + 1) - Boundary_Pos(ii))/real(RegionNodes(ii) - 1, dp)
      end do
    end do
    !!Final Node
    write(vtufile, '(E14.6)', advance='no') Boundary_Pos(N_Regions + 1)
    write(vtufile, '(g0)', advance='no') " 0.000000E+00 0.000000E+00 "

    !!Copy of results smeared in y for vtu visualisation
    Position = 0._dp
    do ii = 1, N_Regions
      do jj = 1, RegionNodes(ii) - 1
        write(vtufile, '(E14.6)', advance='no') Position
        write(vtufile, '(g0)', advance='no') " 0.100000E+01 0.000000E+00 "
        Position = Position + (Boundary_Pos(ii + 1) - Boundary_Pos(ii))/real(RegionNodes(ii) - 1, dp)
      end do
    end do
    !!Final Node
    write(vtufile, '(E14.6)', advance='no') Boundary_Pos(N_Regions + 1)
    write(vtufile, '(g0)', advance='no') " 0.100000E+01 0.000000E+00 "

    write(vtufile, '(g0)') ""
    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)') "</DataArray>"
    write(vtufile, '(g0)', advance='no') "      "
    write(vtufile, '(g0)') "</Points>"

    !!Fill in the cell data
    write(vtufile, '(g0)', advance='no') "      "
    write(vtufile, '(g0)') "<Cells>"

    !!Connectivity
    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)') '<DataArray type="Int32" Name="connectivity" format="ascii">'
    write(vtufile, '(g0)', advance='no') "          "
    do ii = 1, N_Nodes - 1
      write(vtufile, '(g0)', advance='no') ii - 1
      write(vtufile, '(g0)', advance='no') " "
      write(vtufile, '(g0)', advance='no') ii
      write(vtufile, '(g0)', advance='no') " "
      write(vtufile, '(g0)', advance='no') ii + N_Nodes
      write(vtufile, '(g0)', advance='no') " "
      write(vtufile, '(g0)', advance='no') ii - 1 + N_Nodes
      write(vtufile, '(g0)', advance='no') " "
    end do
    write(vtufile, '(g0)') ""
    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)') " </DataArray>"

    !!Offsets
    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)') '<DataArray type="Int32" Name="offsets" format="ascii">'
    write(vtufile, '(g0)', advance='no') "          "
    do ii = 1, N_Nodes - 1
      write(vtufile, '(g0)', advance='no') ii*4
      write(vtufile, '(g0)', advance='no') " "
    end do
    write(vtufile, '(g0)') ""
    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)') " </DataArray>"
    !!Types
    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)', advance='no') "  "
    write(vtufile, '(g0)') '<DataArray type="Int32" Name="types" format="ascii">'
    write(vtufile, '(g0)', advance='no') "          "
    do ii = 1, N_Nodes - 1
      write(vtufile, '(g0)', advance='no') 9
      write(vtufile, '(g0)', advance='no') " "
    end do

    write(vtufile, '(g0)') ""
    write(vtufile, '(g0)', advance='no') "        "
    write(vtufile, '(g0)') " </DataArray>"

    write(vtufile, '(g0)', advance='no') "      "
    write(vtufile, '(g0)') "</Cells>"
    write(vtufile, '(g0)', advance='no') "    "
    write(vtufile, '(g0)') '</Piece>'
    write(vtufile, '(g0)', advance='no') "  "
    write(vtufile, '(g0)') "</UnstructuredGrid>"
    write(vtufile, '(g0)') "</VTKFile>"

    close(vtufile)
    deallocate(Flux)
  end subroutine GenerateVTU

end module
