Module Output_Mod

    use Constants_Mod
    use PETSc_Vec_Mod
    use Problem_Mod
    use Materials_Mod
    !!Handles the data generated by solver routines, generating data readable by paraview etc
    !!Any other postprocessing of data would also go here

    type, public :: t_output

    contains
        procedure, public :: GenerateVTU
    end type
contains

Subroutine GenerateVTU(this,Material,Problem,pVecx)
    Implicit None
    class(t_output) :: this
    type(t_material), dimension(:) :: Material
    type(t_problem) :: Problem 
    type(pVec) :: pVecx
    Integer :: ii, jj, N_Nodes, N_Regions
    Integer, allocatable, dimension(:) :: RegionNodes
    Integer, parameter :: vtufile = 201 
    Real(kind=dp) :: Position
    Real(kind=dp), allocatable, dimension(:) :: Flux, Boundary_Pos
    !!Generate the VTU file using the resultand flux sorted in the PETSc vector x

    !!Extract relevant problem information
    N_Regions = Problem%GetN_Regions()
    Allocate(RegionNodes(N_Regions),Boundary_Pos(N_Regions))
    Boundary_Pos = Problem%GetBoundary_Pos()
    RegionNodes = Problem%GetNodes()
    N_Nodes = Problem%GetN_Nodes()

    !!Extract data from the PETSc vector
    Allocate(Flux(N_Nodes))
    call pVecx%ConvFrom(Flux)

    !!Generate VTU file
    Open(vtufile,File='OutputFile.vtu',Status='Replace')

    !!Describe the format
    Write(vtufile,'(g0)') "<?xml version=""1.0""?>"
    Write(vtufile,'(g0)') "<VTKFile type=""UnstructuredGrid"" version=""0.1"" byte_order=""LittleEndian"">"
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)') "<UnstructuredGrid>"

    !!Describe the amount of data
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') '<Piece NumberOfPoints="'
    Write(vtufile,'(g0)',advance='no') N_Nodes
    Write(vtufile,'(g0)') '" NumberOfCells="0">'


    !!Fill in the point data
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)') '<PointData Scalars="flux">'

    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') '<DataArray Name="flux" format="ascii" type="Float64" />'
    Do ii = 1, N_Nodes
        Write(vtufile,'(E14.6)',advance='no') Flux(ii)
        Write(vtufile,'(g0)',advance='no') " "
    EndDo
    Write(vtufile,'(g0)') ""
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)') "</PointData>"


    !!Fill in the positions of the point data
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)') "<Points>"
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') "<DataArray Name=""Coordinates"" NumberOfComponents=""1"" format=""ascii"" type=""Float64"" />"
    Position = 0._dp
    Do ii = 1, N_Regions
        Do jj = 1, RegionNodes(ii)
            Write(vtufile,'(E14.6)',advance='no') Position
            Write(vtufile,'(g0)',advance='no') " "
            Position = Position + (Boundary_Pos(ii+1)-Boundary_Pos(ii))/Real(RegionNodes(ii),dp)
        EndDo 
    EndDo
    Write(vtufile,'(g0)') ""
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)') "</Points>"

    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)') '</Piece>'

    Write(vtufile,'(g0)',advance='no') "  "
    Write(vtufile,'(g0)') "</UnstructuredGrid>"
    Write(vtufile,'(g0)') "</VTKFile>"

    Close(vtufile)

End Subroutine GenerateVTU

End Module
